# _quarto.yml
project:
  type: website

website:
  title: "DAV"
  navbar:             # Configure the navigation bar
    collapse: true
    pinned: true
    left:             # Links on the left side of the navbar
      - href: index.qmd # Link to your main document
        text: Home    # Text for the link in the navbar
      - href: climate_analyses.qmd
        text: Climate Analyses
      - href: misc.qmd
        text: Misc Tips
      - href: qgis_tips.qmd
        text: QGis
      - href: datasets.qmd
        text: Datasets
  search: true


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    code-summary: "Show Code"

editor: source

# Execution options applied to all R/Python/etc. chunks in the project
execute:
  freeze: false
  echo: true
  warning: false
  message: false
