#' Find a raster cell containing a specific coordinate from a lookup directory
#'
#' @description
#' This function searches a two-level lookup structure (as generated by
#' `spatial_create_lookup`) to find the specific grid cell that contains a
#' given pair of coordinates. It first identifies potential groups by checking
#' the main lookup file, then searches within the relevant group file(s) to
#' find the exact cell.
#'
#' @param coords A numeric vector of length 2: `c(longitude, latitude)`.
#' @param lookup_dir A string path to the 'lookups' directory generated by
#'   `spatial_create_lookup`. This directory must contain `main.csv` and the
#'   `grid_cells` subdirectory.
#' @param crs The Coordinate Reference System (CRS) of the input coordinates,
#'   specified as an EPSG code (e.g., 4326 for WGS 84). Defaults to 4326.
#'
#' @return A list containing the data for the matching cell (id, group_id,
#'   bounding box, and corner coordinates). If no cell is found, returns `NULL`.
#'
#' @importFrom readr read_csv
#' @importFrom sf st_point st_polygon st_sfc st_within
#' @importFrom cli cli_abort
#' @export
#'
#' @examples
#' \dontrun{
#' # First, generate a lookup structure
#' r = terra::rast(xmin = 9, xmax = 17, ymin = 46, ymax = 49,
#'                  resolution = 0.1, crs = "EPSG:4326")
#' r[] = 1:terra::ncell(r)
#' temp_raster_path = file.path(tempdir(), "austria_dummy.tif")
#' terra::writeRaster(r, temp_raster_path, overwrite=TRUE)
#' temp_output_dir = tempdir()
#'
#' spatial_create_lookup(
#'   input_raster_file = temp_raster_path,
#'   output_base_dir = temp_output_dir,
#'   n_groups = 10
#' )
#'
#' # Define the lookup directory
#' lookup_path = file.path(temp_output_dir, "lookups")
#'
#' # Find the cell for a specific coordinate
#' vienna_coords = c(16.3738, 48.2082)
#' found_cell = find_cell_in_lookup(vienna_coords, lookup_path)
#' print(found_cell)
#' }
find_cell_in_lookup = function(coords, lookup_dir, crs = 4326) {

  # --- Input Validation ---
  if (!is.numeric(coords) || length(coords) != 2) {
    cli::cli_abort("`coords` must be a numeric vector of length 2 (lon, lat).")
  }

  main_lookup_path = file.path(lookup_dir, "main.csv")
  grid_cells_dir = file.path(lookup_dir, "grid_cells")

  if (!file.exists(main_lookup_path)) {
    cli::cli_abort("Main lookup file not found at: {.path {main_lookup_path}}")
  }
  if (!dir.exists(grid_cells_dir)) {
    cli::cli_abort("Grid cells directory not found at: {.path {grid_cells_dir}}")
  }

  # --- Bbox check helper ---
  in_bbox = function(lon, lat, xmin, ymin, xmax, ymax) {
    lon >= xmin && lon <= xmax && lat >= ymin && lat <= ymax
  }

  # 1. Read main lookup and find candidate groups
  main_lookup = readr::read_csv(main_lookup_path, show_col_types = FALSE)

  candidate_groups = c()
  for (i in 1:nrow(main_lookup)) {
    group = main_lookup[i, ]
    if (in_bbox(coords[1], coords[2], group$xmin, group$ymin, group$xmax, group$ymax)) {
      candidate_groups = c(candidate_groups, group$id)
    }
  }

  if (length(candidate_groups) == 0) {
    return(NULL)
  }

  # 2. Search within candidate groups
  point = sf::st_point(coords)
  point_sfc = sf::st_sfc(point, crs = crs)

  for (group_id in candidate_groups) {
    group_file_path = file.path(grid_cells_dir, paste0("g_", group_id, ".csv"))
    if (!file.exists(group_file_path)) next

    group_cells = readr::read_csv(group_file_path, show_col_types = FALSE)

    for (j in 1:nrow(group_cells)) {
      cell = group_cells[j, ]

      # First, a quick bbox check
      if (in_bbox(coords[1], coords[2], cell$xmin, cell$ymin, cell$xmax, cell$ymax)) {

        # If bbox matches, do a precise point-in-polygon check
        polygon_coords = matrix(c(
          cell$x_1, cell$y_1,
          cell$x_2, cell$y_2,
          cell$x_3, cell$y_3,
          cell$x_4, cell$y_4,
          cell$x_1, cell$y_1
        ), ncol = 2, byrow = TRUE)

        cell_polygon = sf::st_polygon(list(polygon_coords))
        cell_sfc = sf::st_sfc(cell_polygon, crs = crs)

        if (sf::st_within(point_sfc, cell_sfc, sparse = FALSE)[1, 1]) {
          # Found it! Return the cell data as a list.
          return(as.list(cell))
        }
      }
    }
  }

  # If we get here, no cell was found
  return(NULL)
} 