# .github/workflows/deploy.yml
name: Build and Deploy Sites

on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: write # Allow workflow to write to the gh-pages branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-cli-action@v2
        with:
          # Select the Quarto version matching your project if needed
          version: stable # Or specify e.g., "1.4.549"

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # Or specify a version

      - name: Install R package dependencies (including pkgdown)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::pkgdown
            any::devtools # If needed for installation or examples
            # Add other R dependencies needed for vignettes/pkgdown build
          needs: '"dev"' # Installs Imports, Depends, Suggests

      # Optional: Install your local package if vignettes depend on it being installed
      # - name: Install local package
      #   run: Rscript -e 'devtools::install(".", dependencies = FALSE)'

      - name: Build pkgdown site
        run: Rscript -e 'pkgdown::build_site()'
        working-directory: davR # Run pkgdown from within the package directory

      - name: Render Quarto Project
        run: quarto render wiki --output-dir _site
        # Render explicitly into wiki/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Deploy to the gh-pages branch
          # Deploy pkgdown output (from davR/docs/) to the root of gh-pages
          publish_dir: ./davR/docs
          # Deploy Quarto output (from wiki/_site/) to the /wiki/ subdirectory
          # Note: Use keep_files: true if deploying multiple sources to the same branch
          # This first deploy clears the branch by default.

      # Second deploy step for the wiki content to its subdirectory
      - name: Deploy Wiki to Subdirectory
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./wiki/_site # Deploy the rendered Quarto site
          keep_files: true         # IMPORTANT: Keep files from the previous deploy step
          destination_dir: ./wiki  # Put the wiki site into the 'wiki' subdirectory
