# .github/workflows/deploy.yml
# Workflow to build the pkgdown site for 'davR' package and the Quarto site
# in 'wiki', then deploy both to the 'gh-pages' branch for GitHub Pages.

name: Build and Deploy Sites

#--------------------------------------------------------------------------
# Trigger Conditions
#--------------------------------------------------------------------------
on:
  # Run automatically on pushes to the 'main' branch
  push:
    branches:
      - main # Adjust if your default branch is different (e.g., master)

  # Allow manual triggering from the GitHub Actions tab
  workflow_dispatch:

#--------------------------------------------------------------------------
# Permissions
#--------------------------------------------------------------------------
# Grant necessary permissions for the workflow to push to the gh-pages branch
permissions:
  contents: write

#--------------------------------------------------------------------------
# Job Definition
#--------------------------------------------------------------------------
jobs:
  build-deploy:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      #------------------------------------------------#
      # Step 1: Check out repository code              #
      #------------------------------------------------#
      - name: Check out repository
        uses: actions/checkout@v4 # Downloads repo code to the runner

      #------------------------------------------------#
      # Step 2: Install System Dependencies            #
      #------------------------------------------------#
      # Install OS libraries needed by common R spatial packages (sf, terra, etc.)
      # and others often required (xml2, curl, ssl). Add more if needed.
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            libssl-dev \
            libcurl4-openssl-dev \
            libxml2-dev
          # Add any other system libraries identified from installation errors here

      #------------------------------------------------#
      # Step 3: Set up Quarto and R                    #
      #------------------------------------------------#
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # Add 'with: version: specific-version' if required

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # Use latest stable R release

      #------------------------------------------------#
      # Step 4: Install R Dependencies                 #
      #------------------------------------------------#
      # Uses pak to install R packages listed in DESCRIPTION (via needs: dev)
      # and explicitly specified packages below.
      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Explicitly install these packages. Add others here if needed.
          # Do NOT add YAML comments inside the 'packages' multiline block below.
          packages: |
            any::pkgdown
            any::devtools
            any::httr
          # Add any other direct dependency from davR/DESCRIPTION above if needed
          # Also install Imports, Depends, AND Suggests from local DESCRIPTION file
          needs: dev

      #------------------------------------------------#
      # Step 5: Install the local davR package         #
      #------------------------------------------------#
      # Crucial for pkgdown to find functions and run vignettes using the package
      # Should succeed now that dependencies are installed in Step 4
      - name: Install local davR package
        run: Rscript -e 'devtools::install("davR", upgrade = "never")'

      #------------------------------------------------#
      # Step 6: Build the pkgdown site                 #
      #------------------------------------------------#
      # Runs pkgdown::build_site() within the 'davR' directory
      - name: Build pkgdown site
        run: Rscript -e 'pkgdown::build_site()'
        working-directory: davR # Essential: Run from package root
        # Output defaults to davR/docs/

      #------------------------------------------------#
      # Step 7: Build the Quarto wiki site             #
      #------------------------------------------------#
      # Renders the Quarto project in 'wiki/' to 'wiki/_site/'
      - name: Render Quarto Wiki Project
        run: quarto render wiki --output-dir _site

      #------------------------------------------------#
      # Step 8: Deploy both sites to gh-pages branch   #
      #------------------------------------------------#
      # Uses peaceiris/actions-gh-pages action twice

      # Deploy pkgdown site first (to the root of gh-pages)
      - name: Deploy pkgdown site to Root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatic token for authentication
          publish_branch: gh-pages                # Target branch for deployment
          publish_dir: ./davR/docs                # Source directory (pkgdown output)
          # First deploy clears the branch by default (keep_files defaults to false)

      # Deploy Quarto wiki site second (to the /wiki/ subdirectory on gh-pages)
      - name: Deploy Wiki to /wiki/ Subdirectory
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./wiki/_site                # Source directory (Quarto output)
          keep_files: true                         # *** IMPORTANT: Do not delete pkgdown files ***
          destination_dir: ./wiki                  # *** IMPORTANT: Deploy into 'wiki' subdir ***
          # cname: your.custom.domain.com          # Add if using a custom domain
