# .github/workflows/deploy.yml
# Workflow to build the pkgdown site for 'davR' package (in ./davR)
# and the Quarto site (in ./wiki), then deploy both to the 'gh-pages' branch.
# This workflow only runs when manually triggered.

name: Build and Deploy Sites Manually

#--------------------------------------------------------------------------
# Trigger Conditions
#--------------------------------------------------------------------------
on:
  # Allow manual triggering from the GitHub Actions tab ONLY
  workflow_dispatch:

#--------------------------------------------------------------------------
# Permissions
#--------------------------------------------------------------------------
# Grant necessary permissions for the workflow to push to the gh-pages branch
permissions:
  contents: write

#--------------------------------------------------------------------------
# Job Definition
#--------------------------------------------------------------------------
jobs:
  build-deploy:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      #------------------------------------------------#
      # Step 1: Check out repository code              #
      #------------------------------------------------#
      - name: Check out repository
        uses: actions/checkout@v4 # Downloads repo code to the runner

      #------------------------------------------------#
      # Step 2: Install System Dependencies            #
      #------------------------------------------------#
      # Install OS libraries often needed by R packages (spatial, xml, web)
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            libssl-dev \
            libcurl4-openssl-dev \
            libxml2-dev
          # Add other system libraries here if needed based on R package errors

      #------------------------------------------------#
      # Step 3: Set up Quarto and R                    #
      #------------------------------------------------#
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # Use latest stable R release

      #------------------------------------------------#
      # Step 4: Install R Dependencies                 #
      #------------------------------------------------#
      # Uses pak to install R packages:
      # 1. Explicitly listed essential packages (pkgdown, devtools).
      # 2. Explicitly listed likely direct dependencies (httr, dplyr) - crucial if DESCRIPTION is incomplete.
      # 3. Packages listed in davR/DESCRIPTION (Imports, Depends, Suggests) via 'needs: dev'.
      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # --- IMPORTANT ---
          # List essential build tools and ANY direct package dependencies
          # that caused installation errors in Step 5 previously.
          # DO NOT ADD COMMENTS OR ANYTHING ELSE INSIDE THIS 'packages' BLOCK.
          packages: |
            any::pkgdown
            any::devtools
            any::httr
            any::dplyr
            any::DT
            any::readr
          # If other 'package not found' errors occur in Step 5, add them above.
          # ---
          # Also install dependencies listed in ./davR/DESCRIPTION
          needs: dev

      #------------------------------------------------#
      # Step 5: Install the local davR package         #
      #------------------------------------------------#
      # Installs the package from the ./davR directory.
      # This should now succeed as dependencies were installed in Step 4.
      - name: Install local davR package
        run: Rscript -e 'devtools::install("davR", upgrade = "never")'

      #------------------------------------------------#
      # Step 6: Build the pkgdown site                 #
      #------------------------------------------------#
      # Runs pkgdown::build_site() inside the ./davR directory.
      # Output goes to ./davR/docs/ by default.
      - name: Build pkgdown site
        run: Rscript -e 'pkgdown::build_site()'
        working-directory: davR # Run this command from within the davR folder

      #------------------------------------------------#
      # Step 7: Build the Quarto wiki site             #
      #------------------------------------------------#
      # Renders the Quarto project located in ./wiki/
      # Output goes to ./wiki/_site/
      - name: Render Quarto Wiki Project
        run: quarto render wiki --output-dir _site

      #------------------------------------------------#
      # Step 8: Deploy both sites to gh-pages branch   #
      #------------------------------------------------#
      # Uses peaceiris/actions-gh-pages action twice

      # Deploy pkgdown site first (to the root of gh-pages)
      - name: Deploy pkgdown site to Root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages        # Deploy to the gh-pages branch
          publish_dir: ./davR/docs        # The folder containing the pkgdown site
          # keep_files: false (default)   # Clear the branch on first deploy

      # Deploy Quarto wiki site second (to the /wiki/ subdirectory on gh-pages)
      - name: Deploy Wiki to /wiki/ Subdirectory
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./wiki/_site       # The folder containing the Quarto site
          keep_files: true                # IMPORTANT: Do not delete the pkgdown files
          destination_dir: ./wiki         # IMPORTANT: Put the wiki site into a 'wiki' folder
          # cname: your.custom.domain.com # Uncomment and set if you use a custom domain
